#!/bin/bash

PREFIX=/opt/webide
JDK_HOME=/usr


# if version is not set, get the latest
if [ "$VERSION" == "" ]; then
	VERSION=`basename $(			\
		find $PREFIX	 		\
			-maxdepth 1 		\
			-type d 		\
			-name "WebIDE*" 	\
		| sort -n 			\
		| tail -1 			\
	)`;
fi


WEBIDE_BIN="$PREFIX/$VERSION/bin/webide.sh"
SCRIPT=`basename $WEBIDE_BIN`;

if ! [ -f "$WEBIDE_BIN" ]; then
	echo "$WEBIDE_BIN does not exist!" >&2;
	exit 1;
fi
if ! [ -x "$WEBIDE_BIN" ]; then
	echo "$WEBIDE_BIN is not executable!" >&2
	exit 2;
fi

cd `dirname $WEBIDE_BIN`
export JDK_HOME
exec ./$SCRIPT


